openapi: '3.0.0'
info:
  version: 1.0.0
  title: Smarty Pants Documentation
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /docs:
    get:
      summary: List all docs
      operationId: listDocs
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: An paged array of docs
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Docs'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create doc
      operationId: createDocs
      responses:
        201:
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /docs/{docId}:
    get:
      summary: Info for a doc
      operationId: showDocById
      parameters:
        - name: docId
          in: path
          required: true
          description: The id of the doc to retrieve
          schema:
            type: string
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Docs'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /sections:
    get:
      summary: List all sections
      operationId: listSections
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: An paged array of sections
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sections'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create section
      operationId: createSections
      responses:
        201:
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /sections/{sectionId}:
    get:
      summary: Info for a section
      operationId: showSectionById
      parameters:
        - name: sectionId
          in: path
          required: true
          description: The id of the section to retrieve
          schema:
            type: string
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sections'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Doc:
      required:
        - id
        - title
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        overview:
          type: string
    Docs:
      type: array
      items:
        $ref: '#/components/schemas/Doc'
    Section:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
    Sections:
      type: array
      items:
        $ref: '#/components/schemas/Section'
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string